export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_SUCCES = "ADD_PRODUCT_SUCCES"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"

export const START_DOWNLOAD_PRODUCT = "START_DOWNLOAD_PRODUCT";
export const DOWNLOAD_PRODUCT_SUCCES = "DOWNLOAD_PRODUCT_SUCCES";
export const DOWNLOAD_PRODUCT_ERROR = "DOWNLOAD_PRODUCT_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCES = "PRODUCT_DELETE_SUCCES";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_EDITION_PRODUCT = "START_EDITION_PRODUCT";
export const PRODUCT_EDIT_SUCCES = "PRODUCT_EDIT_SUCCES";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";



